### ISSUE TITLE
Segfault in NativeKafka#close

### ISSUE THREAD

**Issue by peterzhu2118** [appsignal/rdkafka-ruby#278] opened 2023-08-29 20:04 UTC
This is a continuation of confluentinc/librdkafka#4108.

I'm debugging a core dump from a segfault in one of our production systems today. This is the relevant backtrace:

```
#4  0x000055eecec7824d in sigsegv (sig=11, info=0x7f76f5e5c930, ctx=0x7f76f5e5c800) at signal.c:964
#5  <signal handler called>
#6  0x00007f770525faab in __pthread_clockjoin_ex (threadid=threadid@entry=140143353931520, thread_return=thread_return@entry=0x7f75e4ad37e0, clockid=clockid@entry=0, 
    abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:89
#7  0x00007f770526bb7e in thrd_join (thr=thr@entry=140143353931520, res=res@entry=0x7f75e4ad382c) at thrd_join.c:25
#8  0x00007f76f3f8aac7 in rd_kafka_destroy_app (rk=0x7f76c091c800, flags=<optimized out>) at rdkafka.c:1107
#9  0x00007f76fa5c0ff5 in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
#10 0x00007f76fa5c040a in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
#11 0x00007f76f41987e9 in rbffi_CallFunction (argc=<optimized out>, argv=<optimized out>, function=0x7f76f3f8b470 <rd_kafka_destroy>, fnInfo=0x7f76f78466a0) at Call.c:400
#12 0x00007f76f419c787 in custom_trampoline (argc=<optimized out>, argv=<optimized out>, self=<optimized out>, handle=<optimized out>) at MethodHandle.c:220
#13 0x000055eeced07ae5 in vm_call_cfunc_with_frame (ec=0x7f76ecfb46d0, reg_cfp=0x7f75e4bd4150, calling=<optimized out>) at vm_insnhelper.c:3270
```

There are two other threads running:

```
(gdb) info thread
  Id   Target Id                         Frame 
* 1    Thread 0x7f75e4bd6700 (LWP 65954) __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
  2    Thread 0x7f76a99ff700 (LWP 65861) 0x00007f770515ba96 in __ppoll (fds=fds@entry=0x7f76a98fcdd8, nfds=nfds@entry=1, timeout=<optimized out>, timeout@entry=0x0, 
    sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:44
  3    Thread 0x7f7704e63000 (LWP 65800) futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7ffd3c6cd3e0, clockid=<optimized out>, expected=0, futex_word=0x7f7704a4210c)
    at ../sysdeps/nptl/futex-internal.h:320
```

The relevant Ruby level backtrace for thread 1:

```
0x7f75e4bd42d0     METHOD /artifacts/bundle/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/producer.rb close
0x7f75e4bd4290     METHOD /artifacts/bundle/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb close
0x7f75e4bd4250     METHOD /artifacts/bundle/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb synchronize
0x7f75e4bd4210     CFUNC  
0x7f75e4bd41d0     BLOCK  /artifacts/bundle/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb block in synchronize
0x7f75e4bd4190     METHOD /artifacts/bundle/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb with_inner
0x7f75e4bd4150     BLOCK  /artifacts/bundle/ruby/3.2.0/gems/rdkafka-0.13.0/lib/rdkafka/native_kafka.rb block in close
0x7f75e4bd4110     CFUNC  
```

Thread 2 is not relevant for this bug.

I can't show you thread 3 because it's internal code, but it's also in the process of closing Rdkafka::Producer objects.

We're running Ruby 3.2.2, rdkafka 0.13.0, librdkafka 1.2.1-1ubuntu1

**Comment by peterzhu2118** [comment] 2023-08-29 20:04
I suspect #277 might fix this.

**Comment by mensfeld** [comment] 2023-08-29 20:28
@peterzhu2118 you may want to look into how Karafka closes consumers and ensures stability. If you see this crash frequent and is exactly as you described (because there are two other cases that are strictly librdkafka related, reported and fixes are developed), you may try to reproduce it with Karafka. If it won't crash, it means something is off in your code.

Both cases that are on librdkafka present themselves on shutdown and they can be mitigated (one fully, one partially) by finalizing the way karafka does that.

I see your dump is from producer and not consumer (some issues affect one some other). Have you tried waterdrop OR waterdrop finalization method? As far as I can see it should mitigate the issue and it worked for some other crashes because it has a different finalizer flow.

**Comment by peterzhu2118** [comment] 2023-08-29 21:03
I don't think we can easily switch libraries. This is happening in our production system, so I don't think it's trivial for us to switch to a different library.

**Comment by mensfeld** [comment] 2023-08-29 21:13
@peterzhu2118 I am sorry. I misread it and thought you could replicate it in a non-prod env as well.

**Comment by peterzhu2118** [comment] 2023-08-29 21:15
This issue is pretty rare. It only happens a few times per day on a very high traffic app.

**Comment by mensfeld** [comment] 2023-08-29 21:24
>This issue is pretty rare. It only happens a few times per day on a very high traffic app.

And only for producer or consumer as well? There is a known issue related to metadata refreshes and race condition in librdkafka if cluster refresh is happening alongside of shutdown, it may be related.

I understand the limitations of sharing the code but IMHO it could help. Happy to coop in private to tackle this as well-being of this library is extremely important to me :) if you are ok sharing some snippets (not business related but operational of rdkafka-ruby usage) in private we could coop via twitter or slack (http://slack.karafka.io/)

I fixed majority of memory leaks but it may be that opaque or something is not freed as it should or still available on shutdown where it should not. We could try wrapping the WaterDrop shutdown flow around rdkafka-ruby to see if that helps.

Also:

> very high traffic app.

Nature of this traffic could also help and general characteristics of the process. I understand this may not be shareable in public, hence slack. It may be that under heavy stress on async production with some sort of callbacks for instrumentation, there is a problem. For me to diagnose that, I would have to have more details. Otherwise from my side its guessing.

**Comment by mensfeld** [comment] 2023-08-29 21:26
Two last cases I was able to reproduce (for producer and consumer) related to finalization were both librdkafka issues that are still not being fixed. If it turns out to be broker refetch issue, I do know how to mitigate that one.

**Comment by peterzhu2118** [comment] 2023-08-29 23:43
Thank you for all the help @mensfeld! I joined the Slack and DM'd you with more information.

**Comment by mensfeld** [comment] 2023-08-30 09:15
After getting feedback from @peterzhu2118 I can:

1. Replicate the issue
2. Prove it's not rdkafka-ruby issue "per se" because the flow that was presented to me is against the proper termination sequence: https://github.com/confluentinc/librdkafka/blob/master/INTRODUCTION.md#termination and is not freeing resources correctly

**Comment by mensfeld** [comment] 2023-08-30 14:17
Closing for now. We've agreed with @peterzhu2118 to followup later with a purge queue work that anyhow I have in plans and create appropriate card when needed. The repro is as follows:

```ruby
setup_karafka

producer = Rdkafka::Config.new(Karafka::Setup::AttributesMap.producer(Karafka::App.config.kafka.dup)).producer

1000.times do |i|
  producer.produce(
      topic:   "ruby-test-topic",
      payload: "a"
  )
end

a = Thread.new {
  producer.close
}

sleep(0.001)

a.terminate
```

**Closed** 2023-08-30 14:17 UTC
